version: 0.1

log:
  fields:
    service: registry

http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]

storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/docker-cache

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

proxy:
  remoteurl: https://registry-1.docker.io
