apiVersion: v1
kind: Service
metadata:
  name: docker-registry-cache-service
  namespace: docker-cache
  labels:
    app: docker-registry-cache
spec:
  ports:
  - port: 5000
    name: http
    targetPort: 5000
  selector:
    app: docker-registry-cache
